apiVersion: apps/v1 
kind: ReplicaSet 
metadata: 
  name: replicaset-green 
  labels: 
    app: green 
spec:
  replicas: 3 
  selector: 
    matchLabels: 
      app: green 
  template: 
    metadata: 
      labels: 
        app: green 
    spec: 
      containers: 
      - name: container1 
        image: hashicorp/http-echo
        args:
          - "-text=green"

