apiVersion: apps/v1 
kind: ReplicaSet 
metadata: 
  name: replicaset-yellow
  labels: 
    app: yellow
spec:
  replicas: 3 
  selector: 
    matchLabels: 
      app: yellow 
  template: 
    metadata: 
      labels: 
        app: yellow 
    spec: 
      containers: 
      - name: container1 
        image: hashicorp/http-echo
        args:
          - "-text=yellow"

